#!/bin/bash
source script_lib

# $1: gitlabURL
function server_clone()
{
	echo 'clone server...'
	
	pushd $PWD
	cd ../
	mkdir Server
	cd Server
	git clone $1/digame/src/server.git src
	git clone $1/digame/env.git env
	popd
}
function server_pull()
{
	echo 'build server...'
	
	pushd $PWD
	cd ../Server/src
	git checkout -- ./src/digame/go.mod
	git pull
	cd ../Server/env
	git pull
	cd ../Server/env/server/linux/uuidgen
	./uuidgen
	cp server_uuid ../server_uuid
	popd
}
function server_build()
{
	echo 'build server...'
	
	pushd $PWD
	cd src/src/cegame
	export GO111MODULE=on
	
	go build -o ../../../env/server/linux/log_server/logserver.out server/logserver/main.go
	go build -o ../../../env/server/linux/data_server/dataserver.out server/dataserver/main.go
	go build -o ../../../env/server/linux/login_server/loginserver.out server/loginserver/main.go
	go build -o ../../../env/server/linux/lobby_server/lobbyserver.out server/lobbyserver/main.go
	go build -o ../../../env/server/linux/game_server/gameserver.out server/gameserver/main.go
	go build -o ../../../env/server/linux/api_server/apiserver.out server/apiserver/main.go
	popd
}
