#!/bin/bash
source script_lib

# $1: gitlabURL
function server_clone()
{
	echo 'clone server...'

	pushd $PWD > /dev/null
	cd ../Server
	git clone $1/digame/src/server.git src/server
	git clone $1/digame/env.git env
	popd > /dev/null
}
function server_pull()
{
	echo 'pull server...'
	
	pushd $PWD > /dev/null
	cd ../Server/src/server
	git checkout -- ./src/digame/go.mod
	git pull
	cd ../../env
	git pull
	popd > /dev/null
}
function server_build()
{
	echo 'build server...'
	
	pushd $PWD > /dev/null
	cd ../Server/src/server/src/digame
	envPath=../../../../env/server/linux
	export GO111MODULE=on
	
	go build -o $envPath/dataserver/server.out server/dataserver/main.go
	go build -o $envPath/gameserver/server.out server/gameserver/main.go
	go build -o $envPath/betsync/server.out server/betsync/main.go
	go build -o $envPath/betquery/server.out server/betquery/main.go
	
	cp $envPath/dataserver/server.out $envPath/../linux_demo/dataserver/server.out
	cp $envPath/gameserver/server.out $envPath/../linux_demo/gameserver/server.out
	cp $envPath/dataserver/server.out $envPath/../linux_dev/dataserver/server.out
	cp $envPath/gameserver/server.out $envPath/../linux_dev/gameserver/server.out
	popd > /dev/null
	
	pushd $PWD > /dev/null
	cd ../Server/src/server/src/digame
	envPath=../../../../env/wallet/linux
	export GO111MODULE=on
	
	go build -o $envPath/wallet/server.out wallet/wallet/main.go
	popd > /dev/null
	
	pushd $PWD > /dev/null
	cd ../Server/src/server/src/digame
	envPath=../../../../env/wallet.v3/linux
	export GO111MODULE=on
	
	go build -o $envPath/wallet/server.out wallet.v3/wallet/main.go
	popd > /dev/null
}
function server_commit()
{
	echo 'commit server...'
	
	pushd $PWD > /dev/null
	cd ../Server/env
	commit_comment="[src] add. linux server 上版"
	askDefault "commit comment" "commit_comment"
	printf -v commit_comment_escape %b "$commit_comment"
	git add *.out
	git commit -m "$commit_comment_escape"
	git push origin master
	popd > /dev/null
}
# $1: pem, $2: linuxDir, $3: dstURL
function server_deploy_with_key()
{
	echo 'deploy server...'
	
	envPath=../Server/env
	ssh -i $1 $3 'docker-compose -f DockerArea/server/docker-compose.yml down'
	sleep 1
	scp -i $1 -r $envPath/server/$2/* $3:~/Server/server/
	scp -i $1 -r $envPath/wallet/linux/* $3:~/Server/wallet/
	scp -i $1 -r $envPath/wallet.v3/linux/* $3:~/Server/wallet.v3/
	sleep 1
	ssh -i $1 $3 'docker-compose -f DockerArea/server/docker-compose.yml up -d'
}
# $1: password, $2: linuxDir, $3: dstURL
function server_deploy_with_password()
{
	echo 'deploy server...'
	
	envPath=../Server/env
	sshpass -p $1 ssh $3 'docker-compose -f DockerArea/server/docker-compose.yml down'
	sleep 1
	sshpass -p $1 scp -r $envPath/server/$2/* $3:~/Server/server/
	sshpass -p $1 scp -r $envPath/wallet/linux/* $3:~/Server/wallet/
	sshpass -p $1 scp -r $envPath/wallet.v3/linux/* $3:~/Server/wallet.v3/
	sleep 1
	sshpass -p $1 ssh $3 'docker-compose -f DockerArea/server/docker-compose.yml up -d'
}
